'use strict';

var xirr = require('xirr');

var onDeviceReady = function() {
    document.getElementById('calculate').addEventListener('click', calculate);
    document.getElementById('add-rows').addEventListener('click', addRows);
};

var calculate = function(event) {
    event.stopPropagation();
    event.preventDefault();

    var form = document.forms['xirr-form'];
    var txns = [];
    var amount = form.elements.amount;
    var when = form.elements.when;
    for (var i = 0; i < Math.min(amount.length,when.length); i++) {
        if (amount[i].value !== '' && when[i].value !== '') {
            txns.push({
                amount: Number(amount[i].value),
                when: new Date(when[i].value)
            });
        }
    }
    try {
        var result = xirr(txns);
        result = (Math.round(100000*result)/1000);
        document.getElementById('result').textContent = result + '%';
        document.getElementById('message').textContent = getMessage(result);
    } catch (error) {
        document.getElementById('message').textContent = error;
    }
};

var getMessage = function(result) {
    var candidates = messages
        .filter(function(x) { return x.min <= result; })
        .filter(function(x) { return result <= x.max; });
    return candidates[Math.floor(Math.random()*candidates.length)].msg;
};

var addRows = function(event) {
    event.stopPropagation();
    event.preventDefault();

    var inputs = document.getElementById('inputs');
    inputs.appendChild(makeRow());
    inputs.appendChild(makeRow());
    inputs.appendChild(makeRow());
};

var makeRow = function() {
    var div = document.createElement('div');
    var number = document.createElement('input');
    number.type = 'number';
    number.name = 'amount';
    div.appendChild(number);
    var date = document.createElement('input');
    date.type = 'date';
    date.name = 'when';
    div.appendChild(date);
    return div;
};

document.addEventListener('deviceready', onDeviceReady, false);

var messages = [
    { min: -Infinity, max:-95, msg:"Ooh, maybe putting it all on red wasn't the best idea." },
    { min: -Infinity, max:-25, msg:"Ouch, retirement was always an abstract concept for you anyways." },
    { min: -Infinity, max:-10, msg:"Repeat after me, I will not drink the investment wine, I will not drink the investment wine." },
    { min: -200, max: -30, msg:"Guess your second cousin isn't quite as good at poker as he thought." },
    { min: -150, max: -20, msg:"Next time, maybe wait on investing on private space flight until after the company has a successful launch." },
    { min: -100, max:-50, msg:"So Brewster's Millions is wrong, towing a glacier to the desert isn't a good idea?!" },
    { min: -35, max: -3, msg:"They called mortgage-backed securities toxic assets for a reason you know." },
    { min: -25, max: -5, msg:"Really, locally sourced organic mohair baby swaddles?  You what the market for those are?" },
    { min: -15, max: 0, msg:"Contemporary abstract art generated by computers?  You should know better..." },
    { min: -15, max: 0, msg:"Converting to a self-directed IRA to buy a shares in a slaughterhouse?  That takes guts." },
    { min: -15, max: 2, msg:"Looks like phantom shares in your cousin's costume jewelry aren't as profitable as they sound." },
    { min: -15, max: 0, msg:"You know chicken feces are used as fuel in missile launchers, did you really think the DoD would let you sell it as fertilizer?" },
    { min: -15, max: 0, msg:"Short options on a Russian vodka distillery?" },
    { min: -10, max: 10, msg:"You are braver than I am investing in weather derivatives in the Bermuda Triangle." },
    { min: -10, max: 10, msg:"I see you have discovered Bob Dylan's Bowie bonds." },
    { min: -5, max: 0, msg:"Is it YOUR fault the Fed threatened to raise rates again?" },
    { min: 0, max: 2, msg:"May as well have bought savings bonds." },
    { min: 0, max: 8, msg:"Sri Lankan soybean meal, it's not just for breakfast anymore." },
    { min: 0, max: 10, msg:"Organic free-trade haggis from Edinborough can't go wrong." },
    { min: 0, max: 10, msg:"Egyptian lens-makers, I mean the sand is free!" },
    { min: 0, max: 10, msg:"An ostrich egg farm?  How do you keep their heads up?" },
    { min: 3, max: 15, msg:"Salvaging rare coins off the coast of Ecuador, nicely done!" },
    { min: 3, max: 15, msg:"Pork futures from Argentinian lean hogs were all the rage this year." },
    { min: 3, max: 20, msg:"Chinese short options on Canadian long options, you really get in the weeds, don't you?" },
    { min: 3, max: 20, msg:"Albanian hedge funds really know how to get around the regulators." },
    { min: 3, max: 20, msg:"Christmas tree farm, nice, just don't forget to hedge for the off-season." },
    { min: 4, max: 22, msg:"Arabian dressage horses, how did I not see that coming." },
    { min: 5, max: 20, msg:"Hair salon university shares, that can't be a real thing, is it?" },
    { min: 8, max: 15, msg:"Vegan tofurkey futures, who knew?" },
    { min: 10, max: 50, msg:"Vintage USSR stamps, boring but profitable." },
    { min: 10, max: 20, msg:"Yes, collateralized overleveraged micro-securities can be quite profitable." },
    { min: 25, max: Infinity, msg:"Ka-ching!  You know the EULA obligates you to send a piece my way, right?" },
    { min: 50, max: 1000, msg:"Be careful, you can't count on finding a Picasso in every house you flip." },
    { min: 50, max: Infinity, msg:"Can't believe that Formula One performance car sold for that much." },
    { min: 50, max: Infinity, msg:"Takes money to make money when you are investing in Jackson Pollocks." },
    { min: 0, max: 0, msg: "The old mattress, tried and true but it's no inflation hedge." }
];
